# Generated by Django 5.1 on 2025-04-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
