# Generated by Django 5.1 on 2025-05-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_item_vendor_alter_delivery_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expiring_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='item',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
