# Generated by Django 5.1 on 2025-05-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='email',
        ),
    ]
