# Generated by Django 5.1 on 2025-05-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, default=0, max_length=30, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
    ]
