# Generated by Django 5.1 on 2025-05-12 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_item_expiring_date_remove_item_price_and_more'),
        ('transactions', '0002_remove_purchase_vendor_alter_purchase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
