# Generated by Django 5.1 on 2025-05-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_bill_email'),
        ('invoice', '0002_alter_invoice_item'),
        ('transactions', '0003_alter_saledetail_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='amount_change',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='bills.bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful')], default='P', max_length=1, verbose_name='Delivery Status'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='sale',
            table=None,
        ),
        migrations.DeleteModel(
            name='SaleDetail',
        ),
    ]
