# Generated by Django 5.1 on 2025-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_purchase_bill_alter_sale_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful')], default='P', max_length=20, verbose_name='Delivery Status'),
        ),
    ]
