# Generated by Django 5.1 on 2025-06-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_telephone_alter_vendor_phone_number'),
        ('cash', '0002_transaction_added_by_transaction_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
    ]
