# Generated by Django 5.1 on 2025-04-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.CharField(max_length=30),
        ),
    ]
