# Generated by Django 5.1 on 2025-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disinfectant',
            name='min_stock_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='min_stock_level',
            field=models.FloatField(default=0),
        ),
    ]
